# Generated by Django 4.2 on 2024-11-08 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listofcars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listofcars.cars', verbose_name='Машина'),
        ),
    ]
