# Generated by Django 4.2 on 2024-11-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listofcars', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contracts',
            old_name='contractid',
            new_name='contract_id',
        ),
    ]
