# Generated by Django 4.2 on 2024-11-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listofcars', '0003_alter_contracts_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
